#!/bin/sh
# Original /etc/init.d/skeleton modified for http://mydebian.blogdns.org

# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="buddycloud java server"
NAME="buddycloud-server-java"
RUNFROM=/usr/share/buddycloud-server-java
DAEMON=/usr/bin/java
JAR_FILE="$(ls $RUNFROM/channelserver-*-jar-with-dependencies.jar)"
JAR_FILE="$(basename $JAR_FILE)"
DAEMON_ARGS="-XX:-OmitStackTraceInFastThrow -jar $JAR_FILE"
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/buddycloud-server-java

# the user that will run the script
USER=buddycloud

# Make sure only root can run our script
if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root.  Try using sudo." 1>&2
   exit 1
fi


# NO NEED TO MODIFY THE LINES BELOW

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
. /lib/lsb/init-functions

#
# Function that starts the daemon/service
#
do_start()
{

        start-stop-daemon -b --start --quiet --chuid $USER --chdir $RUNFROM -m -p $PIDFILE --exec $DAEMON -- $DAEMON_ARGS \
                || return 2
}

#
# Function that stops the daemon/service
#
do_stop()
{
        start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE
        RETVAL="$?"
        rm -f $PIDFILE
        return "$RETVAL"
}

case "$1" in
  start)
        [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
        do_start
        case "$?" in
                0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
                2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
        esac
        ;;
  stop)
        [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
        do_stop
        case "$?" in
                0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
                2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
        esac
        ;;
  restart|reload|force-reload)
        #
        # If the "reload" option is implemented then remove the
        # 'force-reload' alias
        #
        log_daemon_msg "Restarting $DESC" "$NAME"
        do_stop
        case "$?" in
          0|1)
                # ensure that the XMPP server recognises the port disconnect
                sleep 10
                do_start
                case "$?" in
                        0) log_end_msg 0 ;;
                        1) log_end_msg 1 ;; # Old process is still running
                        *) log_end_msg 1 ;; # Failed to start
                esac
                ;;
          *)
                # Failed to stop
                log_end_msg 1
                ;;
        esac
        ;;
  *)
        echo "Usage: $SCRIPTNAME {start|stop|restart}" >&2
        exit 3
        ;;
esac

:
